language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
  - yarn lint
  - yarn type-check
  - yarn test
