version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn lint
      - run: yarn type-check
      - run: yarn test
